### ISSUE TITLE
How to turn '1 / 1' off on the first page

### ISSUE THREAD

**Issue by ondohotola** [ludwig-austermann/typst-din-5008-letter#3]
I don't like to have the page number on the first page and can't find where/how to turn that off.

How would I do that?

**Comment by ludwig-austermann** [comment]
You can always do something like
```typst
locate(loc =>
  if counter(page).at(loc) != 1 {
    // code for all pages except page 1
  }
)
```
I will look again a it, later.

**Comment by ludwig-austermann** [comment]
Ok, on the last commit (92cd323) it is now possible to set `option.pagenumberonfirstpage = false`.

**Comment by ondohotola** [comment]
Super.

I will try it out and revert.

el

--

**Comment by ondohotola** [comment]
Great effort.

I still have one nit to pick, it looks as if the recipient field will not be displayed in the window of one of these standard window envelopes. I will only be able to stick a sample in one of these on Tuesday at the practice, to confirm, but when I compare this to one of my LyX//LaTeX ones the recipient block looks way too high.

**Comment by ludwig-austermann** [comment]
Note that there are two forms: `Typ A` and `Typ B`. The latter has the recipient field set lower. Anyway, both of these should fit into the standard `DL` envelope (and others for that matter, see [measurements](https://de.wikipedia.org/wiki/Briefumschlag#Deutschland)). Important is here the falzmarke, which is different for both types.

If, however, the sizes are indeed wrong, this is a bug – feel welcome to open another issue then.

**Comment by ondohotola** [comment]
Form |Typ B| works quite nicely from what I can see now.
