### ISSUE TITLE
encl:/cc:

### ISSUE THREAD

**Issue by ondohotola** [ludwig-austermann/typst-din-5008-letter#4]
Ludwig,

after the signature block one sometimes need to list Enclosures or Carbon Copies. Do you think it would be helpful to implement them? So that for example something like

```
#enclosed(Document A,\ Document B)
```

produces something like

```
encl: Document A
      Document B
```

with a (three line space) between the signature block and the enclosure as per
[DIN 5008](https://www.din-5008-richtlinien.de/startseite/anlagenvermerk/).

The cc Block would 1 line distance below the enclosure (or if not there) below the signature block, as per [DIN 5008](https://www.din-5008-richtlinien.de/startseite/verteiler/)

**Comment by ludwig-austermann** [comment]
I have added an attachments option to the letter function. Together with `block-hooks`, the described functionality should be available.
