### ISSUE TITLE
How to get a "Draft" watermark?

### ISSUE THREAD

**Issue by ondohotola** [ludwig-austermann/typst-din-5008-letter#5]
I often uses something like

```typst
#set page(
   background: rotate(
      -35deg,
   text(10em, fill: rgb("E0E0E0"))[Draft, #datetime.today()]
)
```

How would I get this into the letter/template?

I ie I call it from the 

```typst
#{
  defaults.form = "B" // can also be form 'B'
…
  defaults.defaults.draft = [Draft, #datetime.today()]
}
```

to watermark the Draft and Date and like so to do nothing:

```typst
#{
  defaults.form = "B" // can also be form 'B'
…
  defaults.defaults.draft = []
}
```

**Comment by ludwig-austermann** [comment]
In the new version 0.1.0 a background and a foreground styling option are added. Take a look at the example, how one might want to add a watermark.
