### ISSUE TITLE
Feature Request: Package System

### ISSUE THREAD

**Issue by ondohotola** [ludwig-austermann/typst-din-5008-letter#6]
Would it be possible to provide a wrapper for the new [package system](https://typst.app/docs/reference/scripting/#packages), perhaps the [local system](https://github.com/typst/packages)? 

That way one could store the thing in one location and import it from everywhere.

**Comment by ludwig-austermann** [comment]
Oh yes, a local package seems like a very nice idea! I will look into it.

**Comment by ludwig-austermann** [comment]
With the new version 0.1.0, it should be possible to use it as a local package.

**Comment by ondohotola** [comment]
Thanks. GREAT stuff.

After extraction one must install (on the mac) as follows:

```bash
unzip typst-din-5008-letter-main.zip
mv typst-din-5008-letter-main ~/Library/Application\ Support/typst/packages/local/din-5008-letter-0.1.0
```

And the local package import then looks like:

```typst
#import "@local/din-5008-letter:0.1.0": *
```

The examples provided do not work (any more) since `typst` does not go up beyond the document root, so the statement

```typs
#import "../letter.typ" : letter, letter-styling, debug-options, block-hooks
```

can be replaced by

```typst
#import "@local/din-5008-letter:0.1.0": letter, letter-styling, debug-options, block-hooks
```

or shorter

```typst
#import "@local/din-5008-letter:0.1.0": *
```

**Comment by ludwig-austermann** [comment]
Yes I think this should work exactly as you described.
